"""
generate.py -- Analytic (closed-form) true Pareto front generators for the
ZDT, DTLZ, and Mixed_* benchmark problems, plus a fallback approximate
reference-front builder (used for the EvoPINN problems, which have no known
closed-form front). Each `true_front_*` function returns an (n, n_obj)
array of points sampled directly from the known Pareto-optimal set/front
shape for that problem, rather than being derived from any optimizer run.
"""

import numpy as np

from nondominated_sort import pareto_front, unique_rows


# helpers
def _simplex_points(n, m, rng):
    """Uniform points on the unit simplex sum(w)=1, w>=0 (Dirichlet)."""
    w = rng.dirichlet(np.ones(m), size=n)
    return w


def _sphere_points(n, m, rng):
    """Uniform-ish points on the positive octant of the unit sphere."""
    v = np.abs(rng.normal(size=(n, m)))
    return v / np.linalg.norm(v, axis=1, keepdims=True)


# ZDT family (all minimise)
def true_front_zdt1(n=1000, **kw):
    """Convex front: f2 = 1 - sqrt(f1), f1 in [0,1]."""
    f1 = np.linspace(0.0, 1.0, n)
    return np.column_stack([f1, 1.0 - np.sqrt(f1)])


def true_front_zdt2(n=1000, **kw):
    """Concave (non-convex) front: f2 = 1 - f1^2."""
    f1 = np.linspace(0.0, 1.0, n)
    return np.column_stack([f1, 1.0 - f1 ** 2])


def true_front_zdt3(n=1000, **kw):
    """Disconnected front: oversample then keep only the non-dominated
    points, so the resulting curve naturally shows the disjoint segments
    caused by the sin(10*pi*f1) term."""
    f1 = np.linspace(0.0, 1.0, 5 * n)
    f2 = 1.0 - np.sqrt(f1) - f1 * np.sin(10.0 * np.pi * f1)
    F = np.column_stack([f1, f2])
    F = pareto_front(F, objective_types=['min', 'min'])
    idx = np.linspace(0, len(F) - 1, min(n, len(F))).astype(int)  # thin down to ~n points
    return F[idx]


def true_front_zdt4(n=1000, **kw):
    """Same front shape as ZDT1 (ZDT4 differs from ZDT1 only in its landscape
    of local optima, not its true Pareto front)."""
    return true_front_zdt1(n)


def true_front_zdt6(n=1000, **kw):
    """Non-uniformly distributed, concave front starting at f1=0.280775
    (ZDT6's characteristic bias towards larger f1 values)."""
    f1 = np.linspace(0.280775, 1.0, n)
    return np.column_stack([f1, 1.0 - f1 ** 2])


# DTLZ family (all minimise, M = 3 here)
def true_front_dtlz1(n=1000, m=3, seed=0, **kw):
    """Linear hyperplane front: sum(f) = 0.5, sampled via a Dirichlet simplex."""
    rng = np.random.default_rng(seed)
    return 0.5 * _simplex_points(n, m, rng)


def true_front_dtlz2(n=1000, m=3, seed=0, **kw):
    """Spherical front: sum(f_i^2) = 1, sampled on the positive-octant unit sphere."""
    rng = np.random.default_rng(seed)
    return _sphere_points(n, m, rng)


true_front_dtlz3 = true_front_dtlz2   # DTLZ3 differs from DTLZ2 only in landscape ruggedness, same true front
true_front_dtlz4 = true_front_dtlz2   # DTLZ4 differs from DTLZ2 only in the density bias along the front


def true_front_dtlz5(n=1000, m=3, **kw):
    """Degenerate curve: theta_2..theta_{M-1} = pi/4."""
    t1 = np.linspace(0.0, np.pi / 2, n)
    c, s = np.cos(t1), np.sin(t1)
    q = np.pi / 4
    f1 = c * np.cos(q)
    f2 = c * np.sin(q)
    f3 = s
    return np.column_stack([f1, f2, f3])


true_front_dtlz6 = true_front_dtlz5   # DTLZ6 shares DTLZ5's degenerate-curve front shape

def true_front_dtlz7(n=1000, m=3, seed=0, **kw):
    """Disconnected, mixed convex/concave front (4 disjoint patches for m=3).
    Generated by sampling the decision-space form directly, applying the
    DTLZ7 g/h formulas, then keeping only the non-dominated, de-duplicated
    result (oversampling 8x to get enough coverage after filtering)."""
    rng = np.random.default_rng(seed)
    x = rng.random((8 * n, m - 1))
    g = 1.0
    h = m - np.sum(x / (1 + g) * (1 + np.sin(3 * np.pi * x)), axis=1)
    fM = (1 + g) * h
    F = np.column_stack([x, fM])
    F = pareto_front(F, objective_types=['min'] * m)
    F, _ = unique_rows(F)
    if len(F) > n:
        idx = rng.choice(len(F), size=n, replace=False)
        F = F[idx]
    return F


# Mixed min/max problems  
def true_front_mixed_zdt1(n=1000, **kw):
    """min f1 = x1 ; max f2 = sqrt(x1)/g  ->  g = 1 gives f2 = sqrt(f1)."""
    f1 = np.linspace(0.0, 1.0, n)
    return np.column_stack([f1, np.sqrt(f1)])


def true_front_mixed_dtlz1(n=1000, seed=0, **kw):
    """min f1, min f2, max f3 with f3 = f1 + f2 on the plane, f1+f2 <= 0.5."""
    rng = np.random.default_rng(seed)
    w = rng.dirichlet(np.ones(2), size=n)
    s = 0.5 * rng.random(n) ** 0.5          # bias towards the outer edge
    f1 = w[:, 0] * s
    f2 = w[:, 1] * s
    return np.column_stack([f1, f2, f1 + f2])


def true_front_mixed_dtlz2(n=1000, seed=0, **kw):
    """min f1, min f2, max f3 on the cone f3 = sqrt(f1^2 + f2^2), f3 in [0,1]."""
    rng = np.random.default_rng(seed)
    phi = rng.random(n) * (np.pi / 2)
    r = rng.random(n) ** 0.5
    return np.column_stack([r * np.cos(phi), r * np.sin(phi), r])


# EvoPINN 
def approximate_reference_front(list_of_F, objective_types, max_size=1000,
                               seed=0):
    """Non-dominated union of many archives — used when no analytic PF exists.

    Stacks every run's final front together, filters down to the mutually
    non-dominated set (the best "reference" we can construct without a known
    ground truth), de-duplicates, and randomly subsamples down to max_size if
    the result is larger (keeps downstream metric computation affordable)."""
    stacks = [np.asarray(F, dtype=float) for F in list_of_F if len(F)]
    if not stacks:
        return np.zeros((0, len(objective_types)))
    allF = np.vstack(stacks)
    allF = allF[np.all(np.isfinite(allF), axis=1)]
    if len(allF) == 0:
        return np.zeros((0, len(objective_types)))
    F = pareto_front(allF, objective_types=objective_types)
    F, _ = unique_rows(F)
    if len(F) > max_size:
        rng = np.random.default_rng(seed)
        F = F[rng.choice(len(F), size=max_size, replace=False)]
    return F


# Registry mapping problem name -> its true_front generator function, used by
# dataset.py's STANDARD_BUILDERS/MIXED_BUILDERS to attach `true_front` to
# each problem dict.
TRUE_FRONTS = {
    'ZDT1': true_front_zdt1, 'ZDT2': true_front_zdt2, 'ZDT3': true_front_zdt3,
    'ZDT4': true_front_zdt4, 'ZDT6': true_front_zdt6,
    'DTLZ1': true_front_dtlz1, 'DTLZ2': true_front_dtlz2,
    'DTLZ3': true_front_dtlz3, 'DTLZ4': true_front_dtlz4,
    'DTLZ5': true_front_dtlz5, 'DTLZ6': true_front_dtlz6,
    'DTLZ7': true_front_dtlz7,
    'Mixed_ZDT1': true_front_mixed_zdt1,
    'Mixed_DTLZ1': true_front_mixed_dtlz1,
    'Mixed_DTLZ2': true_front_mixed_dtlz2,
}
